# Generated by Django 5.0.2 on 2024-02-10 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("show_car", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="car_list",
            new_name="carList",
        ),
    ]
