# Generated by Django 4.2.7 on 2024-02-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_car', '0002_rename_car_list_carlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='chassisNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carlist',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
