# Generated by Django 4.2.7 on 2024-02-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_car', '0004_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
