# Generated by Django 4.2.7 on 2024-02-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show_car', '0006_carlist_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='show_car.showroom'),
        ),
    ]
